version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - "2181"
    networks:
      - shared_network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_REPLICA_FETCH_MAX_BYTES: 200000000
      KAFKA_FETCH_MAX_BYTES: 200000000
      KAFKA_MAX_REQUEST_SIZE: 2000000000  
      KAFKA_MESSAGE_MAX_BYTES: 2000000000 
    expose:
      - "9092"
    networks:
      - shared_network

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
    expose:
      - "9000"
    networks:
      - shared_network

  news-service:
    image: ghcr.io/mperestoronin/classifier:latest
    container_name: news_service
    env_file:
      - .env
    depends_on:
      - kafka
    networks:
      - shared_network

  digest-service:
    image: ghcr.io/mperestoronin/digest-creator:latest
    container_name: digest_service
    env_file:
      - .env
    expose:
      - "5000"
    networks:
      - shared_network

  mailman:
    image: ghcr.io/mperestoronin/mailman:latest
    container_name: mailman
    env_file:
      - .env
    expose:
      - "5001"
    networks:
      - shared_network

  frontend:
    image: ghcr.io/mperestoronin/frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - shared_network

networks:
  shared_network:
    external: true
